exports.run = async (client, message, args) => {
    var util = require("../fivem");
    message.delete();
    let embed = new Discord.RichEmbed()
    .setAuthor(state, icon)
    .setColor(color)
    .setDescription(`**ZentriX Bot - Comandos:**`)
    //.addField(`Melhor servidor`, "ZentriX RP - discord.gg/436xBCR")
    .addBlankField(true)
    //.addField(`${config.prefix}set <serverIP:port>`, "Define o servidor FiveM da discord atual")
    //.addField(`${config.prefix}players`, "Obtém a lista de jogadores atual de um servidor")
    //.addField(`${config.prefix}server`, "Obtém a lista de jogadores atual de um servidor")
    //.addField(`${config.prefix}find <username>`, "Localiza um usuário que está no servidor via Nome de usuário")
    //.addField(`${config.prefix}id <id>`, "Localiza um usuário que está no servidor via Server ID")
    //.addField(`${config.prefix}status`, "Checks if the server is online")
    //.addField(`${config.prefix}stats`, "Checa as est do bot")
    //.addField(`${config.prefix}save-log <person's server id>`, "Salva as informações de um jogador")
    //.addField(`${config.prefix}get-log`, "Obtém as informações de um jogador (por discord)")
    //.addField(`${config.prefix}forum <topic>`, "Searches the latest topics in the categories on https://forum.fivem.net")
    //.addField(`${config.prefix}forum `, "Checks the current categories on https://forum.fivem.net")
    //.addField(`${config.prefix}forum search <search terms>`, "Searches terms on https://forum.fivem.net")
    //.addField(`${config.prefix}forum user <username>`, "Searches user's info on https://forum.fivem.net")
    //.addField(`${config.prefix}native <search terms>`, "returns a specific GTAV native that you searched for")
    //.addField(`${config.prefix}rcon help`, "Comandos da VPS/RCON")
    //.addField(`${config.prefix}rcon set <rcon_password>`, "Define o servidor rcon da guilda ")
    //.addField(`${config.prefix}rcon <rcon_command>`, "Executa um [comando RCON](https://docs.fivem.net/server-manual/server-commands/)")
    .addField(`${config.prefix}ping`, "Pong?")
    .addField(`${config.prefix}love`, "Calcula seu amor seu com outra pessoa. Exemplo: $love @Abraão")
    .addField(`${config.prefix}meme`, "Procuro um meme bem daora e mando aqui")
    .addField(`${config.prefix}insta`, "Pego informações do instagram desejado. Exemplo: $insta nome-da-conta")
    //.addBlankField(true)
    .setThumbnail(icon)
    //.setTitle("Support Discord")
    //.setURL("https://discord.gg/436xBCR")
    //.addBlankField(true)
    //.addField("No", news)
    //.setFooter("Copyright © Zua - https://github.com/thatziv/", icon)
    log(`Comando de ajuda solicitado.. em: ${message.guild.name}`)
  
    message.channel.send({embed: embed})
};
